name: deploy

on:
  push:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: deploy
      run: yarn deploy
