name: deploy

on:
  push:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: deploy
      run: yarn deploy
